//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransSkin2Model.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransSkin2Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;variants&quot;: {
        ///        &quot;facing=east,half=bottom,shape=straight&quot;:  { &quot;model&quot;: &quot;sandstone_stairs&quot;, &quot;y&quot;: 90, &quot;uvlock&quot;: false },
        ///        &quot;facing=west,half=bottom,shape=straight&quot;:  { &quot;model&quot;: &quot;sandstone_stairs&quot;, &quot;y&quot;: 270, &quot;uvlock&quot;: false },
        ///        &quot;facing=south,half=bottom,shape=straight&quot;: { &quot;model&quot;: &quot;sandstone_stairs&quot;, &quot;y&quot;: 180, &quot;uvlock&quot;: false },
        ///        &quot;facing=north,half=bottom,shape=straight&quot;: { &quot;model&quot;: &quot;sandstone_stairs&quot; },
        ///
        ///        &quot;facing=east,half=bottom,shape=outer_right&quot;:  { &quot;model&quot;: &quot;sandstone [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string blockstats_MiniNor {
            get {
                return ResourceManager.GetString("blockstats_MiniNor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;variants&quot;: {
        ///        &quot;facing=east,half=bottom,shape=straight&quot;:  { &quot;model&quot;: &quot;jungle_stairs&quot;, &quot;y&quot;: 90, &quot;uvlock&quot;: false },
        ///        &quot;facing=west,half=bottom,shape=straight&quot;:  { &quot;model&quot;: &quot;jungle_stairs&quot;, &quot;y&quot;: 270, &quot;uvlock&quot;: false },
        ///        &quot;facing=south,half=bottom,shape=straight&quot;: { &quot;model&quot;: &quot;jungle_stairs&quot;, &quot;y&quot;: 180, &quot;uvlock&quot;: false },
        ///        &quot;facing=north,half=bottom,shape=straight&quot;: { &quot;model&quot;: &quot;jungle_stairs&quot; },
        ///
        ///        &quot;facing=east,half=bottom,shape=outer_right&quot;:  { &quot;model&quot;: &quot;jungle_outer_stairs&quot;, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string blockstats_MiniSin {
            get {
                return ResourceManager.GetString("blockstats_MiniSin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;variants&quot;: {
        ///        &quot;facing=east,half=bottom,shape=straight&quot;:  { &quot;model&quot;: &quot;spruce_stairs&quot;, &quot;y&quot;: 90, &quot;uvlock&quot;: false },
        ///        &quot;facing=west,half=bottom,shape=straight&quot;:  { &quot;model&quot;: &quot;spruce_stairs&quot;, &quot;y&quot;: 270, &quot;uvlock&quot;: false },
        ///        &quot;facing=south,half=bottom,shape=straight&quot;: { &quot;model&quot;: &quot;spruce_stairs&quot;, &quot;y&quot;: 180, &quot;uvlock&quot;: false },
        ///        &quot;facing=north,half=bottom,shape=straight&quot;: { &quot;model&quot;: &quot;spruce_stairs&quot; },
        ///
        ///        &quot;facing=east,half=bottom,shape=outer_right&quot;:  { &quot;model&quot;: &quot;spruce_outer_stairs&quot;, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string blockstats_Nor {
            get {
                return ResourceManager.GetString("blockstats_Nor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;variants&quot;: {
        ///        &quot;facing=east,half=bottom,shape=straight&quot;:  { &quot;model&quot;: &quot;birch_stairs&quot;, &quot;y&quot;: 90, &quot;uvlock&quot;: false },
        ///        &quot;facing=west,half=bottom,shape=straight&quot;:  { &quot;model&quot;: &quot;birch_stairs&quot;, &quot;y&quot;: 270, &quot;uvlock&quot;: false },
        ///        &quot;facing=south,half=bottom,shape=straight&quot;: { &quot;model&quot;: &quot;birch_stairs&quot;, &quot;y&quot;: 180, &quot;uvlock&quot;: false },
        ///        &quot;facing=north,half=bottom,shape=straight&quot;: { &quot;model&quot;: &quot;birch_stairs&quot; },
        ///
        ///        &quot;facing=east,half=bottom,shape=outer_right&quot;:  { &quot;model&quot;: &quot;birch_outer_stairs&quot;, &quot;y&quot;: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string blockstats_Sin {
            get {
                return ResourceManager.GetString("blockstats_Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;__creator&quot;: &quot;IceLitty&quot;,
        ///    &quot;__createdwith&quot;: &quot;opl&apos;s Model Creator&quot;,
        ///    &quot;ambientocclusion&quot;: false,
        ///    &quot;textures&quot;: {
        ///        &quot;skin&quot;: &quot;blocks/skin&quot;
        ///    },
        ///    &quot;elements&quot;: [
        ///        {
        ///            &quot;from&quot;: [6,0,7],
        ///            &quot;to&quot;: [8,2,9],
        ///            &quot;faces&quot;: {
        ///                &quot;up&quot;: {
        ///                    &quot;uv&quot;: [1,4,2,5],
        ///                    &quot;texture&quot;: &quot;#skin&quot;
        ///                },
        ///                &quot;down&quot;: {
        ///                    &quot;uv&quot;: [2,5,3,4],
        ///                    &quot;texture&quot;: &quot;#skin&quot;
        ///                },
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MiniSkinJson_Nor {
            get {
                return ResourceManager.GetString("MiniSkinJson_Nor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;__creator&quot;: &quot;IceLitty&quot;,
        ///    &quot;__createdwith&quot;: &quot;opl&apos;s Model Creator&quot;,
        ///    &quot;ambientocclusion&quot;: false,
        ///    &quot;textures&quot;: {
        ///        &quot;skin&quot;: &quot;blocks/skin_sin&quot;
        ///    },
        ///    &quot;elements&quot;: [
        ///        {
        ///            &quot;from&quot;: [6,0,7],
        ///            &quot;to&quot;: [8,2,9],
        ///            &quot;faces&quot;: {
        ///                &quot;up&quot;: {
        ///                    &quot;uv&quot;: [1,4,2,5],
        ///                    &quot;texture&quot;: &quot;#skin&quot;
        ///                },
        ///                &quot;down&quot;: {
        ///                    &quot;uv&quot;: [2,5,3,4],
        ///                    &quot;texture&quot;: &quot;#skin&quot;
        ///                },
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MiniSkinJson_Sin {
            get {
                return ResourceManager.GetString("MiniSkinJson_Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;pack&quot;: {
        ///    &quot;pack_format&quot;: 1,
        ///    &quot;description&quot;: &quot;Auto Create Skin Models. __by IceLitty&quot;
        ///  }
        ///} 的本地化字符串。
        /// </summary>
        internal static string packMcmeta {
            get {
                return ResourceManager.GetString("packMcmeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap skin {
            get {
                object obj = ResourceManager.GetObject("skin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap skin_sin {
            get {
                object obj = ResourceManager.GetObject("skin_sin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;__creator&quot;: &quot;IceLitty&quot;,
        ///    &quot;__createdwith&quot;: &quot;opl&apos;s Model Creator&quot;,
        ///    &quot;ambientocclusion&quot;: false,
        ///    &quot;textures&quot;: {
        ///        &quot;skin&quot;: &quot;blocks/skin&quot;
        ///    },
        ///    &quot;elements&quot;: [
        ///        {
        ///            &quot;from&quot;: [4,-0.5,6],
        ///            &quot;to&quot;: [8,11.5,10],
        ///            &quot;__comment&quot;: &quot;Right Leg&quot;,
        ///            &quot;faces&quot;: {
        ///                &quot;up&quot;: {
        ///                    &quot;uv&quot;: [1,4,2,5],
        ///                    &quot;texture&quot;: &quot;#skin&quot;
        ///                },
        ///                &quot;down&quot;: {
        ///                    &quot;uv&quot;: [2,5,3,4],
        ///                  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SkinJson_Nor {
            get {
                return ResourceManager.GetString("SkinJson_Nor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;__creator&quot;: &quot;IceLitty&quot;,
        ///    &quot;__createdwith&quot;: &quot;opl&apos;s Model Creator&quot;,
        ///    &quot;ambientocclusion&quot;: false,
        ///    &quot;textures&quot;: {
        ///        &quot;skin&quot;: &quot;blocks/skin_sin&quot;
        ///    },
        ///    &quot;elements&quot;: [
        ///        {
        ///            &quot;from&quot;: [4,-0.5,6],
        ///            &quot;to&quot;: [8,11.5,10],
        ///            &quot;__comment&quot;: &quot;Right Leg&quot;,
        ///            &quot;faces&quot;: {
        ///                &quot;up&quot;: {
        ///                    &quot;uv&quot;: [1,4,2,5],
        ///                    &quot;texture&quot;: &quot;#skin&quot;
        ///                },
        ///                &quot;down&quot;: {
        ///                    &quot;uv&quot;: [2,5,3,4],
        ///              [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SkinJson_Sin {
            get {
                return ResourceManager.GetString("SkinJson_Sin", resourceCulture);
            }
        }
    }
}
